export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const FETCH_PROFILE = 'fetchProfile'
export const UPDATE_PROFILE = 'updateProfile'
